# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAPazriMhMi-OGq9RsUffNt4hyggUSqK
"""

import pandas as pd

file_path = 'netflix_titles.csv'
netflix_data = pd.read_csv(file_path)
netflix_data.head()

import matplotlib.pyplot as plt
type_counts = netflix_data['type'].value_counts()

plt.figure(figsize=(8, 6))
type_counts.plot(kind='bar', color=['skyblue', 'salmon'])
plt.title('Number of Movies vs TV Shows')
plt.xlabel('Type')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

if 'date_added' not in netflix_data.columns:
    raise KeyError("The dataframe does not contain a 'date_added' column.")

netflix_data['date_added'] = pd.to_datetime(netflix_data['date_added'], errors='coerce')

if netflix_data['date_added'].isnull().any():
    print("Warning: Some 'date_added' values were invalid and have been set to NaT (Not a Time).")

netflix_data = netflix_data.dropna(subset=['date_added'])

netflix_data['month_added'] = netflix_data['date_added'].dt.month

monthly_releases = netflix_data['month_added'].value_counts().sort_index()

plt.figure(figsize=(10, 6))
monthly_releases.plot(kind='bar', color='lightgreen')
plt.title('Number of Releases per Month')
plt.xlabel('Month')
plt.ylabel('Number of Releases')
plt.xticks(rotation=0)
plt.show()

if 'imdb_rating' in netflix_data.columns:
    top_rated_movies = netflix_data[netflix_data['type'] == 'Movie'].sort_values(by='imdb_rating', ascending=False).head(10)

    print(top_rated_movies[['title', 'imdb_rating']])

top_countries = netflix_data['country'].value_counts().head(10)

plt.figure(figsize=(12, 6))
top_countries.plot(kind='bar', color='orchid')
plt.title('Top 10 Content Creating Countries')
plt.xlabel('Country')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.show()